version: '2'

services:
  db:
      image: postgres:13.1
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./proj/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        - POSTGRES_DB=exchange_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  proj:
      user: root
      build: ./proj
      volumes:
        - ./proj:/deploy
      ports:
        - "12345:12345"
      depends_on:
        - db

